//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIClient.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetData", ReplyAction="http://tempuri.org/IDataService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetData", ReplyAction="http://tempuri.org/IDataService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserLinks", ReplyAction="http://tempuri.org/IDataService/GetUserLinksResponse")]
        string GetUserLinks(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserLinks", ReplyAction="http://tempuri.org/IDataService/GetUserLinksResponse")]
        System.Threading.Tasks.Task<string> GetUserLinksAsync(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertLinkOrCreateUser", ReplyAction="http://tempuri.org/IDataService/InsertLinkOrCreateUserResponse")]
        string InsertLinkOrCreateUser(string fullLink, System.Nullable<int> userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertLinkOrCreateUser", ReplyAction="http://tempuri.org/IDataService/InsertLinkOrCreateUserResponse")]
        System.Threading.Tasks.Task<string> InsertLinkOrCreateUserAsync(string fullLink, System.Nullable<int> userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : UIClient.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<UIClient.DataService.IDataService>, UIClient.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetUserLinks(string guid) {
            return base.Channel.GetUserLinks(guid);
        }
        
        public System.Threading.Tasks.Task<string> GetUserLinksAsync(string guid) {
            return base.Channel.GetUserLinksAsync(guid);
        }
        
        public string InsertLinkOrCreateUser(string fullLink, System.Nullable<int> userId) {
            return base.Channel.InsertLinkOrCreateUser(fullLink, userId);
        }
        
        public System.Threading.Tasks.Task<string> InsertLinkOrCreateUserAsync(string fullLink, System.Nullable<int> userId) {
            return base.Channel.InsertLinkOrCreateUserAsync(fullLink, userId);
        }
    }
}
